// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: userSchema.proto
// Protobuf Java Version: 4.27.3

package com.romys.proto.user;

public interface CompanyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.Company)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.user.Address address = 2;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.user.Address address = 2;</code>
   * @return The address.
   */
  com.romys.proto.user.Address getAddress();
  /**
   * <code>.user.Address address = 2;</code>
   */
  com.romys.proto.user.AddressOrBuilder getAddressOrBuilder();
}
