// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: userSchema.proto
// Protobuf Java Version: 4.27.3

package com.romys.proto.user;

public interface UserListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .user.User users = 1;</code>
   */
  java.util.List<com.romys.proto.user.User> 
      getUsersList();
  /**
   * <code>repeated .user.User users = 1;</code>
   */
  com.romys.proto.user.User getUsers(int index);
  /**
   * <code>repeated .user.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .user.User users = 1;</code>
   */
  java.util.List<? extends com.romys.proto.user.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .user.User users = 1;</code>
   */
  com.romys.proto.user.UserOrBuilder getUsersOrBuilder(
      int index);
}
