// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: userSchema.proto
// Protobuf Java Version: 4.27.3

package com.romys.proto.user;

public final class UserSchema {
  private UserSchema() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      UserSchema.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_user_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_Company_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_user_Company_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_user_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_user_UserList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020userSchema.proto\022\004user\"9\n\007Address\022\017\n\007a" +
      "ddress\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\017\n\007country\030\003 " +
      "\001(\t\"7\n\007Company\022\014\n\004name\030\001 \001(\t\022\036\n\007address\030" +
      "\002 \001(\0132\r.user.Address\"\217\001\n\004User\022\n\n\002id\030\001 \001(" +
      "\005\022\020\n\010fullName\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\016\n\006gend" +
      "er\030\004 \001(\t\022\036\n\007address\030\005 \001(\0132\r.user.Address" +
      "\022\036\n\007company\030\006 \001(\0132\r.user.Company\022\014\n\004role" +
      "\030\007 \001(\t\"%\n\010UserList\022\031\n\005users\030\001 \003(\0132\n.user" +
      ".UserB\030\n\024com.romys.proto.userP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_user_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_user_Address_descriptor,
        new java.lang.String[] { "Address", "City", "Country", });
    internal_static_user_Company_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_Company_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_user_Company_descriptor,
        new java.lang.String[] { "Name", "Address", });
    internal_static_user_User_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_user_User_descriptor,
        new java.lang.String[] { "Id", "FullName", "Age", "Gender", "Address", "Company", "Role", });
    internal_static_user_UserList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_UserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_user_UserList_descriptor,
        new java.lang.String[] { "Users", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
